export const ESCALATION_THRESHOLDS = {
  UNACKNOWLEDGED_SEV1_MINUTES: 15,
  UNACKNOWLEDGED_SEV2_MINUTES: 30,
  UNRESOLVED_SEV1_HOURS: 4,
  UNRESOLVED_SEV2_HOURS: 12,
  OVERLOADED_OWNER_CRITICAL_COUNT: 3,
  COMPONENT_RECURRENCE_THRESHOLD: 2,
};
